name: mlexpensereport
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  intl: ^0.18.1
  get_it: ^7.2.0
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  flutter_dotenv: ^5.0.0
  fluttertoast: ^8.0.7
  xml: ^6.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env