import '../models/expense_report.dart';

List<ExpenseReport> getExpenseData() {
  return [
    ExpenseReport(
        employeeId: '001',
        department: 'Engineering',
        companyName: 'Amazing Airlines',
        dateSubmitted: '2022-12-31',
        expenseCategory: 'Travel',
        currency: 'USD',
        amount: 100.00,
        taxInformation: 'Tax Exempt',
        businessReason: 'Conference',
        projectCode: 'ABC123',
        status: 'rejected',
        additionalNotes: 'Flight was cancelled due to weather conditions.'),
    ExpenseReport(
        employeeId: '002',
        department: 'Marketing',
        companyName: 'TV Streaming Service',
        dateSubmitted: '2023-11-30',
        expenseCategory: 'Subscription',
        currency: 'USD',
        amount: 200.00,
        taxInformation: 'N/A',
        businessReason: 'Monthly Subscription',
        projectCode: 'DEF456',
        status: 'approved',
        additionalNotes: 'N/A'),
    ExpenseReport(
        employeeId: '003',
        department: 'Sales',
        companyName: 'Online Course',
        dateSubmitted: '2020-10-01',
        expenseCategory: 'Training',
        currency: 'USD',
        amount: 300.00,
        taxInformation: 'Tax Exempt',
        businessReason: 'Online Course',
        projectCode: 'GHI789',
        status: 'pending',
        additionalNotes: 'Training is required for new project.'),
    ExpenseReport(
        employeeId: '002',
        department: 'Sales',
        companyName: 'Superb Hotels',
        dateSubmitted: '2022-11-20',
        expenseCategory: 'Accommodation',
        currency: 'USD',
        amount: 200.00,
        taxInformation: 'Taxable',
        businessReason: 'Client meeting',
        projectCode: 'DEF456',
        status: 'approved',
        additionalNotes: 'Stayed for 3 nights for a client meeting.'),
    ExpenseReport(
        employeeId: '003',
        department: 'Marketing',
        companyName: 'Delicious Restaurants',
        dateSubmitted: '2022-12-15',
        expenseCategory: 'Meals',
        currency: 'USD',
        amount: 50.00,
        taxInformation: 'Tax Exempt',
        businessReason: 'Team dinner',
        projectCode: 'GHI789',
        status: 'pending',
        additionalNotes: 'Team dinner after product launch.'),
    ExpenseReport(
        employeeId: '004',
        department: 'Human Resources',
        companyName: 'Reliable Rentals',
        dateSubmitted: '2023-01-05',
        expenseCategory: 'Transport',
        currency: 'USD',
        amount: 3000.00,
        taxInformation: 'Taxable',
        businessReason: 'Office relocation',
        projectCode: 'JKL012',
        status: 'rejected',
        additionalNotes: 'Car rental for office relocation.')
  ];
}
